// <auto-generated />
using System;
using App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace bd_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("App.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PWZNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("App.ExaminationDictionary", b =>
                {
                    b.Property<int>("ExaminationDictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<char>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ExaminationDictionaryId");

                    b.ToTable("ExaminationsDictionary");
                });

            modelBuilder.Entity("App.LaboratoryExamination", b =>
                {
                    b.Property<int>("LaboratoryExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApprovalRejectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExaminationDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExaminationDictionaryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LaboratoryManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LaboratoryWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenagerComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientVisitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("LaboratoryExaminationId");

                    b.HasIndex("ExaminationDictionaryId");

                    b.HasIndex("LaboratoryManagerId");

                    b.HasIndex("LaboratoryWorkerId");

                    b.HasIndex("PatientVisitId");

                    b.ToTable("LaboratoryExaminations");
                });

            modelBuilder.Entity("App.LaboratoryManager", b =>
                {
                    b.Property<int>("LaboratoryManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("LaboratoryManagerId");

                    b.ToTable("LaboratoryManagers");
                });

            modelBuilder.Entity("App.LaboratoryWorker", b =>
                {
                    b.Property<int>("LaboratoryWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("LaboratoryWorkerId");

                    b.ToTable("LaboratoryWorkers");
                });

            modelBuilder.Entity("App.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PESEL")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("App.PatientVisit", b =>
                {
                    b.Property<int>("PatientVisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReceptionistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientVisitId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReceptionistId");

                    b.ToTable("PatientVisits");
                });

            modelBuilder.Entity("App.PhysicalExamination", b =>
                {
                    b.Property<int>("PhysicalExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExaminationDictionaryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.HasKey("PhysicalExaminationId");

                    b.HasIndex("ExaminationDictionaryId");

                    b.ToTable("PhysicalExaminations");
                });

            modelBuilder.Entity("App.Receptionist", b =>
                {
                    b.Property<int>("ReceptionistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ReceptionistId");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("App.LaboratoryExamination", b =>
                {
                    b.HasOne("App.ExaminationDictionary", null)
                        .WithMany("LaboratoryExaminations")
                        .HasForeignKey("ExaminationDictionaryId");

                    b.HasOne("App.LaboratoryManager", null)
                        .WithMany("CheckedExaminations")
                        .HasForeignKey("LaboratoryManagerId");

                    b.HasOne("App.LaboratoryWorker", null)
                        .WithMany("PerformedExaminations")
                        .HasForeignKey("LaboratoryWorkerId");

                    b.HasOne("App.PatientVisit", null)
                        .WithMany("OrderedExaminations")
                        .HasForeignKey("PatientVisitId");
                });

            modelBuilder.Entity("App.PatientVisit", b =>
                {
                    b.HasOne("App.Doctor", null)
                        .WithMany("PerformedVisits")
                        .HasForeignKey("DoctorId");

                    b.HasOne("App.Patient", null)
                        .WithMany("PatientVisits")
                        .HasForeignKey("PatientId");

                    b.HasOne("App.Receptionist", null)
                        .WithMany("RegisteredVisits")
                        .HasForeignKey("ReceptionistId");
                });

            modelBuilder.Entity("App.PhysicalExamination", b =>
                {
                    b.HasOne("App.ExaminationDictionary", null)
                        .WithMany("PhysicalExaminations")
                        .HasForeignKey("ExaminationDictionaryId");
                });
#pragma warning restore 612, 618
        }
    }
}
